[build]
  publish = "."

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[plugins]]
  package = "@netlify/plugin-sitemap"

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200

[functions]
  node_bundler = "esbuild"
